[package]
name = "meshr"
version = "0.1.0"
edition = "2021"

[dependencies]
flate2 = "1.0"
nalgebra = "0.33"
rayon = "1.10"

[dev-dependencies]
criterion = "0.5"
rand = "0.8"

[profile.dev]
opt-level = 3

[[bench]]
name = "collision"
harness = false
