
# cargo-vet config file

[cargo-vet]
version = "0.10"

[[exemptions.adler2]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.aho-corasick]]
version = "1.1.3"
criteria = "safe-to-run"

[[exemptions.anes]]
version = "0.1.6"
criteria = "safe-to-run"

[[exemptions.anstyle]]
version = "1.0.10"
criteria = "safe-to-run"

[[exemptions.approx]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.autocfg]]
version = "1.4.0"
criteria = "safe-to-deploy"

[[exemptions.bumpalo]]
version = "3.16.0"
criteria = "safe-to-run"

[[exemptions.bytemuck]]
version = "1.21.0"
criteria = "safe-to-deploy"

[[exemptions.byteorder]]
version = "1.5.0"
criteria = "safe-to-run"

[[exemptions.cast]]
version = "0.3.0"
criteria = "safe-to-run"

[[exemptions.cfg-if]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.ciborium]]
version = "0.2.2"
criteria = "safe-to-run"

[[exemptions.ciborium-io]]
version = "0.2.2"
criteria = "safe-to-run"

[[exemptions.ciborium-ll]]
version = "0.2.2"
criteria = "safe-to-run"

[[exemptions.clap]]
version = "4.5.21"
criteria = "safe-to-run"

[[exemptions.clap_builder]]
version = "4.5.21"
criteria = "safe-to-run"

[[exemptions.clap_lex]]
version = "0.7.3"
criteria = "safe-to-run"

[[exemptions.crc32fast]]
version = "1.4.2"
criteria = "safe-to-deploy"

[[exemptions.criterion]]
version = "0.5.1"
criteria = "safe-to-run"

[[exemptions.criterion-plot]]
version = "0.5.0"
criteria = "safe-to-run"

[[exemptions.crossbeam-deque]]
version = "0.8.5"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-epoch]]
version = "0.9.18"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-utils]]
version = "0.8.20"
criteria = "safe-to-deploy"

[[exemptions.crunchy]]
version = "0.2.2"
criteria = "safe-to-run"

[[exemptions.either]]
version = "1.13.0"
criteria = "safe-to-deploy"

[[exemptions.flate2]]
version = "1.0.35"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.15"
criteria = "safe-to-run"

[[exemptions.half]]
version = "2.4.1"
criteria = "safe-to-run"

[[exemptions.hermit-abi]]
version = "0.4.0"
criteria = "safe-to-run"

[[exemptions.is-terminal]]
version = "0.4.13"
criteria = "safe-to-run"

[[exemptions.itertools]]
version = "0.10.5"
criteria = "safe-to-run"

[[exemptions.itoa]]
version = "1.0.11"
criteria = "safe-to-run"

[[exemptions.js-sys]]
version = "0.3.72"
criteria = "safe-to-run"

[[exemptions.libc]]
version = "0.2.162"
criteria = "safe-to-run"

[[exemptions.log]]
version = "0.4.22"
criteria = "safe-to-run"

[[exemptions.matrixmultiply]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.7.4"
criteria = "safe-to-run"

[[exemptions.miniz_oxide]]
version = "0.8.3"
criteria = "safe-to-deploy"

[[exemptions.nalgebra]]
version = "0.33.2"
criteria = "safe-to-deploy"

[[exemptions.nalgebra-macros]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.num-bigint]]
version = "0.4.6"
criteria = "safe-to-deploy"

[[exemptions.num-complex]]
version = "0.4.6"
criteria = "safe-to-deploy"

[[exemptions.num-integer]]
version = "0.1.46"
criteria = "safe-to-deploy"

[[exemptions.num-rational]]
version = "0.4.2"
criteria = "safe-to-deploy"

[[exemptions.num-traits]]
version = "0.2.19"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.20.2"
criteria = "safe-to-run"

[[exemptions.oorandom]]
version = "11.1.4"
criteria = "safe-to-run"

[[exemptions.paste]]
version = "1.0.15"
criteria = "safe-to-deploy"

[[exemptions.plotters]]
version = "0.3.7"
criteria = "safe-to-run"

[[exemptions.plotters-backend]]
version = "0.3.7"
criteria = "safe-to-run"

[[exemptions.plotters-svg]]
version = "0.3.7"
criteria = "safe-to-run"

[[exemptions.ppv-lite86]]
version = "0.2.20"
criteria = "safe-to-run"

[[exemptions.proc-macro2]]
version = "1.0.89"
criteria = "safe-to-deploy"

[[exemptions.quote]]
version = "1.0.37"
criteria = "safe-to-deploy"

[[exemptions.rand]]
version = "0.8.5"
criteria = "safe-to-run"

[[exemptions.rand_chacha]]
version = "0.3.1"
criteria = "safe-to-run"

[[exemptions.rand_core]]
version = "0.6.4"
criteria = "safe-to-run"

[[exemptions.rawpointer]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.rayon]]
version = "1.10.0"
criteria = "safe-to-deploy"

[[exemptions.rayon-core]]
version = "1.12.1"
criteria = "safe-to-deploy"

[[exemptions.regex]]
version = "1.11.1"
criteria = "safe-to-run"

[[exemptions.regex-automata]]
version = "0.4.9"
criteria = "safe-to-run"

[[exemptions.regex-syntax]]
version = "0.8.5"
criteria = "safe-to-run"

[[exemptions.ryu]]
version = "1.0.18"
criteria = "safe-to-run"

[[exemptions.safe_arch]]
version = "0.7.4"
criteria = "safe-to-deploy"

[[exemptions.same-file]]
version = "1.0.6"
criteria = "safe-to-run"

[[exemptions.serde]]
version = "1.0.215"
criteria = "safe-to-run"

[[exemptions.serde_derive]]
version = "1.0.215"
criteria = "safe-to-run"

[[exemptions.serde_json]]
version = "1.0.132"
criteria = "safe-to-run"

[[exemptions.simba]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.87"
criteria = "safe-to-deploy"

[[exemptions.tinytemplate]]
version = "1.2.1"
criteria = "safe-to-run"

[[exemptions.typenum]]
version = "1.17.0"
criteria = "safe-to-deploy"

[[exemptions.unicode-ident]]
version = "1.0.13"
criteria = "safe-to-deploy"

[[exemptions.walkdir]]
version = "2.5.0"
criteria = "safe-to-run"

[[exemptions.wasi]]
version = "0.11.0+wasi-snapshot-preview1"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen]]
version = "0.2.95"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen-backend]]
version = "0.2.95"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.95"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.95"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.95"
criteria = "safe-to-run"

[[exemptions.web-sys]]
version = "0.3.72"
criteria = "safe-to-run"

[[exemptions.wide]]
version = "0.7.32"
criteria = "safe-to-deploy"

[[exemptions.winapi-util]]
version = "0.1.9"
criteria = "safe-to-run"

[[exemptions.windows-sys]]
version = "0.52.0"
criteria = "safe-to-run"

[[exemptions.windows-sys]]
version = "0.59.0"
criteria = "safe-to-run"

[[exemptions.windows-targets]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_aarch64_msvc]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_i686_gnu]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_i686_gnullvm]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_i686_msvc]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_x86_64_gnu]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_x86_64_msvc]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.zerocopy]]
version = "0.7.35"
criteria = "safe-to-run"

[[exemptions.zerocopy-derive]]
version = "0.7.35"
criteria = "safe-to-run"
