[package]
name = "meshr-python"
version = "0.1.0"
edition = "2021"

[lib]
name = "meshr"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22.6", features = ["extension-module"] }

[dependencies.meshr]
path = "../../"
